library(Seurat)
library(ggplot2)
library(future)
library(dplyr)
library(openxlsx)

# snRNA-seq data input 
control1 <- Read10X("snRNA_seq_injury/Matrix/1OD3.Matrix/filtered_feature_bc_matrix/")
control2 <- Read10X("snRNA_seq_injury/Matrix/3OD3.Matrix/filtered_feature_bc_matrix/")
injury1 <- Read10X("snRNA_seq_injury/Matrix/2OS3.Matrix/filtered_feature_bc_matrix/")
injury2 <- Read10X("snRNA_seq_injury/Matrix/3OS3.Matrix/filtered_feature_bc_matrix/")
seurat.list<-list(control1=control1,control2=control2,injury1=injury1,injury2=injury2)
rm(control1,control2,injury1,injury2);gc()

# crate seurat object
for (i in 1:length(seurat.list)) {
  seurat.list[[i]] <- CreateSeuratObject(seurat.list[[i]],
                                         project = names(seurat.list)[i], 
                                         min.cells = 3,
                                         min.features = 200,
  )
}


# quality control
dir.create("snRNA_seq_injury/results/QC",recursive = T)
## QC
for (i in 1:length(seurat.list)) {
  VlnPlot(seurat.list[[i]], features = c("nFeature_RNA", "nCount_RNA"), ncol = 2,pt.size = 0)
  ggsave(filename = paste0("snRNA_seq_injury/results/QC/QC-VlnPlot_",names(seurat.list)[i],".pdf"),width = 6,height = 4.5)
  a <- seurat.list[[i]]@meta.data
  ggplot(data = a,aes(x = a$nCount_RNA))+geom_density(fill="pink")+xlim(c(0,30000))
  ggsave(filename = paste0("snRNA_seq_injury/results/QC/QC-nCount.density_",names(seurat.list)[i],".pdf"),width = 6,height = 4.5)
  ggplot(data = a,aes(x = a$nFeature_RNA))+geom_density(fill="pink")+xlim(c(0,10000))
  ggsave(filename = paste0("snRNA_seq_injury/results/QC/QC-nFeature.density_",names(seurat.list)[i],".pdf"),width = 6,height = 4.5)
}


# filter threshold: Feature_RNA > 300 & nFeature_RNA < quantile(seurat_sample, 0.975)
## control1
cat(names(seurat.list)[1],": Before filter ",nrow(seurat.list[[1]]@meta.data),"cells\n") #Before filter : 8940 cells
seurat.list[[1]] <- subset(seurat.list[[1]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 4234)
cat(names(seurat.list)[1],": After filter ",nrow(seurat.list[[1]]@meta.data),"cells\n") #Before filter : 8714 cells

## control2
cat(names(seurat.list)[2],": Before filter ",nrow(seurat.list[[2]]@meta.data),"cells\n") #Before filter : 6877 cells
seurat.list[[2]] <- subset(seurat.list[[2]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 5091)
cat(names(seurat.list)[2],": After filter ",nrow(seurat.list[[2]]@meta.data),"cells\n") #Before filter : 6736 cells

## injury1
cat(names(seurat.list)[3],": Before filter ",nrow(seurat.list[[3]]@meta.data),"cells\n") #Before filter : 9427 cells
seurat.list[[3]] <- subset(seurat.list[[3]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 4778)
cat(names(seurat.list)[3],": After filter ",nrow(seurat.list[[3]]@meta.data),"cells\n") #Before filter : 9106 cells

## injury2
cat(names(seurat.list)[4],": Before filter ",nrow(seurat.list[[4]]@meta.data),"cells\n") #Before filter : 11987 cells
seurat.list[[4]] <- subset(seurat.list[[4]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 4927)
cat(names(seurat.list)[4],": After filter ",nrow(seurat.list[[4]]@meta.data),"cells\n") #Before filter : 11684 cells

save(seurat.list,file = "snRNA_seq_injury/results/seurat.list.Rdata")
# SCTransform
seurat.list <- lapply(X = seurat.list, FUN = SCTransform )
features <- SelectIntegrationFeatures(object.list = seurat.list, nfeatures = 3000)
seurat.list <- PrepSCTIntegration(object.list = seurat.list, anchor.features = features)
seurat.obj.anchors <- FindIntegrationAnchors(object.list = seurat.list, normalization.method = "SCT", anchor.features = features)
seurat.obj.combined <- IntegrateData(anchorset = seurat.obj.anchors, normalization.method = "SCT")

# setting group
seurat.obj.combined <- RenameIdents(seurat.obj.combined,
                                    "control1"="control",
                                    "control2"="control",
                                    "injury1"="injury",
                                    "injury2"="injury")
seurat.obj.combined$group <- Idents(seurat.obj.combined)

# PCA
seurat.obj.combined <- RunPCA(seurat.obj.combined, verbose = FALSE)


# dir.create
dir.create("snRNA_seq_injury/results/SCT.CCA/1.data input & merge", recursive = T)


# ElbowPlot
pdf(paste0("snRNA_seq_injury/results/SCT.CCA/data input & merge/PCA-ElbowPlot.pdf"),width = 6,height = 5)
ElbowPlot(seurat.obj.combined,ndims = 50)
dev.off()


# choose dimention
dim.use <- 1:30


# clustering
seurat.obj.combined <- FindNeighbors(seurat.obj.combined, dims = dim.use,reduction = "pca")
seurat.obj.combined <- FindClusters(seurat.obj.combined, resolution = 0.6,method = "igraph",algorithm = 4)

# UMAP reduction
seurat.obj.combined <- RunUMAP(seurat.obj.combined, reduction = "pca", dims = dim.use)

# change default assay
DefaultAssay(seurat.obj.combined) <- "RNA"

# findallmarkers
allmarker <- FindAllMarkers(seurat.obj.combined,logfc.threshold = 0.5,only.pos = T,min.pct = 0.25)
openxlsx::write.xlsx(allmarker,file = "snRNA_seq_injury/results/SCT.CCA/1.data input & merge/findallmarker res0.6 log2fc0.5.xlsx",rowNames=T)

# scale data
seurat.obj.combined <- ScaleData(seurat.obj.combined,features = rownames(seurat.obj.combined))

# RenameIdents
seurat.obj.combined <- RenameIdents(seurat.obj.combined,
                                    "1"="Astrocyte",
                                    "2"="MP",
                                    "3"="Astrocyte",
                                    "4"="Astrocyte",
                                    "5"="Oligodendrocyte",
                                    "6"="Fibroblast",
                                    "7"="Astrocyte",
                                    "8"="Fibroblast",
                                    "9"="OPC",
                                    "10"="VEC",
                                    "11"="Fibroblast",
                                    "12"="Undefined",
                                    "13"="VEC",
                                    "14"="Vascular Mural Cell",
                                    "15"="Oligodendrocyte",
                                    "16"="MP",
                                    "17"="VEC",
                                    "18"="Oligodendrocyte",
                                    "19"="Astrocyte")

seurat.obj.combined <- RenameIdents(seurat.obj.combined,
                                    "1"="Oligodendrocyte",
                                    "2"="MP",
                                    "3"="Astrocyte",
                                    "4"="Astrocyte",
                                    "5"="Astrocyte",
                                    "6"="Fibroblast",
                                    "7"="VEC",
                                    "8"="Astrocyte",
                                    "9"="OPC",
                                    "10"="Astrocyte",
                                    "11"="Fibroblast",
                                    "12"="Vascular Mural Cell",
                                    "13"="Fibroblast",
                                    "14"="VEC",
                                    "15"="Astrocyte",
                                    "16"="Astrocyte")

seurat.obj.combined$celltype <- Idents(seurat.obj.combined)

# drop outlier cells (Cells that are apparently far from the position of the cell population coordinates are discarded)
## old
seurat.obj.combined <- subset(seurat.obj.combined, cells=c("CGCATAAAGCTACTAC-1_1",
                                                            "CATCCCATCTGCGGCA-1_1",
                                                            "GCAGCTGGTCACTGAT-1_1",
                                                            "CCGGGTAAGGTGCCAA-1_1",
                                                            "TTCCAATAGCTTTCCC-1_1",
                                                            "AGACTCATCAAGGCTT-1_1",
                                                            "TTCCTTCAGTGCTCGC-1_1",
                                                            "AAAGGGCTCGAGATGG-1_1",
                                                            "TCATCCGGTGTCTCCT-1_1",
                                                            "GGCAGTCGTGTGTCGC-1_1",
                                                            "TGTGCGGAGACATCCT-1_1",
                                                            "AACGGGAAGTTGAATG-1_1",
                                                            "CCCTAACGTAGAGGAA-1_1",
                                                            "TGTAGACCAGAGCCCT-1_1",
                                                            "CTCAAGACAGACCAAG-1_1",
                                                            "TCGAACACAGCAGAAC-1_1",
                                                            "CGGGACTCAACCGATT-1_1",
                                                            "TTCTTCCAGCTAATCC-1_1",
                                                            "AGTTAGCTCTGACAGT-1_1",
                                                            "CTTCTCTGTTGGAGAC-1_1",
                                                            "TCTCTGGCACGCACCA-1_1",
                                                            "GGGCTACGTAATCAGA-1_1",
                                                            "AACGGGATCAGTAGGG-1_1",
                                                            "ACATCCCGTTCGTGCG-1_1",
                                                            "CGTGTCTCAGGTTCCG-1_1",
                                                            "GGCTTGGCAAGTCCAT-1_1",
                                                            "GAAGCGAGTCGAGTGA-1_1",
                                                            "AATCACGAGTTCCGTA-1_1",
                                                            "GACAGCCCACACAGAG-1_1",
                                                            "GTAGAGGCACAATGAA-1_1",
                                                            "CACTAAGTCCCGTTCA-1_1",
                                                            "GAGGCCTTCTTCGGTC-1_1",
                                                            "TCGGTCTTCCGTACGG-1_1",
                                                            "CTTCAATTCAATGTCG-1_1",
                                                            "ATTGGGTAGGTTTGAA-1_1",
                                                            "ACCAACAGTTCTCTCG-1_1",
                                                            "CGCATAACACACGTGC-1_1",
                                                            "TAACCAGAGACCAGCA-1_1",
                                                            "TATATCCCATTCTCCG-1_1",
                                                            "CCGATGGCATGGAATA-1_1",
                                                            "ACCTGTCGTACGAAAT-1_1",
                                                            "ACTTTCACATTGAGCT-1_1",
                                                            "ATCCACCTCCACTTTA-1_1",
                                                            "CCCATTGGTCTTGCTC-1_1",
                                                            "GTCATGATCGTCAGAT-1_1",
                                                            "CTGTACCAGTTCGCAT-1_1",
                                                            "AGGTAGGGTAGCCAGA-1_1",
                                                            "TCCTGCAAGTGAGCCA-1_1",
                                                            "ATTCCATTCGATTGAC-1_1",
                                                            "GGCACGTAGCTAGTTC-1_1",
                                                            "TCCGGGAAGCTAGCCC-1_1",
                                                            "AATCACGCAGATCCAT-1_1",
                                                            "AGAAGTAAGGACGCTA-1_1",
                                                            "CCAAGCGGTCCTTGTC-1_1",
                                                            "AGATCGTCACTCGATA-1_1",
                                                            "ATCCGTCGTGGCCCAT-1_1",
                                                            "AAAGGTATCGAAGGAC-1_1",
                                                            "CTGTAGAGTACTAAGA-1_1",
                                                            "CAGATTGGTGTCCATA-1_1",
                                                            "ATGGATCGTTCCGGTG-1_1",
                                                            "TCCGATCAGGCTAGCA-1_1",
                                                            "ATGAGTCGTACGATGG-1_1",
                                                            "CTCGAGGTCGAAGAAT-1_1",
                                                            "GTTGAACAGGACTGGT-1_1",
                                                            "GTAGAAAGTGGTCTGC-1_1",
                                                            "CTCATCGAGGGAGGAC-1_1",
                                                            "GGTTGTAAGGTACATA-1_1",
                                                            "TCCCACAGTCGCAACC-1_1",
                                                            "ACGATGTGTGTCTTAG-1_1",
                                                            "GACCCAGGTGGTCCCA-1_1",
                                                            "CGTCAAAAGGCATGCA-1_1",
                                                            "TCCTTCTAGGGCTGAT-1_1",
                                                            "ACCTACCAGTAACGAT-1_1",
                                                            "CACGTGGGTACGAAAT-1_1",
                                                            "TCTTAGTAGTGCCGAA-1_1",
                                                            "GACCCAGTCGATCCCT-1_1",
                                                            "GGTCTGGCACTGCATA-1_1",
                                                            "ATTTCTGGTAGAAACT-1_1",
                                                            "AACCAACTCCGGACTG-1_1",
                                                            "ATTCACTGTCTAATCG-1_1",
                                                            "TCCACCAGTTTGTGGT-1_1",
                                                            "TCGGGACTCGAGTCTA-1_1",
                                                            "GTAGAAATCCACTGGG-1_1",
                                                            "ACCCAAAAGAATACAC-1_1",
                                                            "GATCCCTGTGTTGCCG-1_1",
                                                            "CTTGATTCATGACGAG-1_1",
                                                            "ACCTACCAGGCTCACC-1_1",
                                                            "AATGCCACAGCAGTAG-1_1",
                                                            "TTCTAACGTCAACATC-1_1",
                                                            "ATACTTCCACGGCCAT-1_1",
                                                            "CATGCAACAAGTGATA-1_1",
                                                            "AAGATAGAGTTGCTCA-1_1",
                                                            "GTCTGTCGTTGACTGT-1_1",
                                                            "TGGAGGAAGCCTCACG-1_1",
                                                            "TTCTAGTGTTACCGTA-1_1",
                                                            "AACGAAAAGATCGCTT-1_1",
                                                            "GAGAGGTTCAAGTCGT-1_1",
                                                            "GTGGCGTCATCGTCCT-1_1",
                                                            "TCACTATTCCGCACGA-1_1",
                                                            "TTGTTTGTCTAGCAAC-1_1",
                                                            "CTGAGCGCAGTATGAA-1_1",
                                                            "ACGCACGGTCGTATGT-1_1",
                                                            "ACCAACAGTGAGCTCC-1_1",
                                                            "TGTACAGAGGTAGTCG-1_1",
                                                            "TCTATACGTTGGATCT-1_1",
                                                            "TTGAACGCAGTGCGCT-1_1",
                                                            "CCTACGTAGATTGACA-1_1",
                                                            "TGACAGTGTCTGCATA-1_1",
                                                            "CGATGGCTCAGCGTCG-1_1",
                                                            "TGCTCCAAGACCTCAT-1_1",
                                                            "TCCTCGAAGTCAGCCC-1_1",
                                                            "TTCAGGAAGCCTGACC-1_1",
                                                            "AACACACGTCACTGAT-1_1",
                                                            "GGTGTTATCAAGCTGT-1_1",
                                                            "CAAGCTAGTGTCTAAC-1_1",
                                                            "CAATGACTCTTTGGAG-1_2",
                                                            "AGACCCGCAAGGATGC-1_2",
                                                            "ATCGCCTCAGTTAGGG-1_2",
                                                            "TTCGGTCCACTGCATA-1_2",
                                                            "GCCATTCAGAATTCAG-1_2",
                                                            "GAGTTGTAGGTTTACC-1_2",
                                                            "AGACACTTCCGCGATG-1_2",
                                                            "CCTCTCCTCGAGCACC-1_2",
                                                            "CATCGGGCAGAAATTG-1_2",
                                                            "CATTGAGTCGTCCATC-1_2",
                                                            "GCACGTGCAGGTTTAC-1_2",
                                                            "TGTCCCAAGGCTATCT-1_2",
                                                            "AATGCCACAAGGTCTT-1_2",
                                                            "GTCATGACACTATCGA-1_2",
                                                            "TGCACGGGTGCTCTTC-1_2",
                                                            "CAAGACTAGATCCTAC-1_2",
                                                            "ACCTACCGTCCAGAAG-1_2",
                                                            "TACTTGTAGAGGGTGG-1_2",
                                                            "ATTCAGGCAACATACC-1_2",
                                                            "CTCCCTCGTGGACAGT-1_2",
                                                            "ACGATGTAGGATCATA-1_2",
                                                            "GTTATGGAGTGAGTTA-1_2",
                                                            "GATTCGAGTGCTCTCT-1_2",
                                                            "AGAAATGCACATTCTT-1_2",
                                                            "CTACCTGGTCACTTCC-1_2",
                                                            "TACCGGGTCCGGCAGT-1_2",
                                                            "GAACACTAGCTGGCCT-1_2",
                                                            "TCATTCAAGTCGGGAT-1_2",
                                                            "TGGTACACACTTCAGA-1_2",
                                                            "CGAGTTACAATACCCA-1_2",
                                                            "GCCCGAACACCTGTCT-1_2",
                                                            "ATCCATTAGCGGGTAT-1_2",
                                                            "TGATTCTTCCAGCTCT-1_2",
                                                            "ATGACCAAGACTTAAG-1_2",
                                                            "TTATTGCCACATACTG-1_2",
                                                            "GAGAAATAGGTCCTGC-1_2",
                                                            "TATCTGTCACAGAGAC-1_2",
                                                            "ACCACAATCCGTGTCT-1_2",
                                                            "GGGTCTGTCTGAGAGG-1_2",
                                                            "AGTGCCGTCTCCACTG-1_2",
                                                            "TGCATCCCAATAGGAT-1_2",
                                                            "ACTCCCACAACCAATC-1_2",
                                                            "AAGCGAGAGGGAGATA-1_2",
                                                            "CCCAACTCACTGGATT-1_2",
                                                            "AGTGACTCATGACACT-1_2",
                                                            "GCCATGGAGTTGTACC-1_2",
                                                            "CGAGAAGTCATCGACA-1_2",
                                                            "TCAATTCGTCATAAAG-1_2",
                                                            "TACGGGCGTGAATTGA-1_2",
                                                            "GCAGCTGAGACCATAA-1_2",
                                                            "ACAACCATCGGAAACG-1_2",
                                                            "CCGAACGTCTACTGCC-1_2",
                                                            "GCATTAGTCTACGCAA-1_2",
                                                            "AGTGATCTCAGGGATG-1_2",
                                                            "TTCAGGATCGTCGACG-1_2",
                                                            "AACCAACGTGCTAGCC-1_2",
                                                            "AAGTACCGTACAGTCT-1_2",
                                                            "GAAACCTAGCGAATGC-1_2",
                                                            "GGGCTCAGTATCGTAC-1_2",
                                                            "TCCCAGTTCAGCTTCC-1_2",
                                                            "ATTTCTGAGTTTGGCT-1_2",
                                                            "CGTGAATCATCAGCGC-1_2",
                                                            "CCTTCAGTCGATCCCT-1_2",
                                                            "CGAAGGAAGGTGATAT-1_2",
                                                            "ACTGATGAGCCTGAAG-1_2",
                                                            "ACATGCAAGGTGGGTT-1_2",
                                                            "GAGTTACAGGGTTAGC-1_2",
                                                            "ATTCCCGAGGGTTGCA-1_2",
                                                            "GTGTTAGTCTTTCAGT-1_2",
                                                            "GTGTGATTCCGGACGT-1_2",
                                                            "CGCCATTTCTCGGGAC-1_2",
                                                            "CAAGGGACAGGACGAT-1_2",
                                                            "AAGACTCTCTTTACAC-1_2",
                                                            "CATCCGTAGGCACGAT-1_2",
                                                            "AAGTGAAAGTCGAAAT-1_2",
                                                            "CTTCCGAAGCAAGTGC-1_2",
                                                            "GAAGCCCAGTTGGAGC-1_2",
                                                            "GCAGTTAAGCACGATG-1_2",
                                                            "TTTGGTTCAAATTAGG-1_2",
                                                            "GAGGGATGTCGTGCCA-1_2",
                                                            "TGAATCGCAGCAATTC-1_2",
                                                            "ACCTACCAGTTGGAAT-1_2",
                                                            "CATGCCTCAGTCGTTA-1_2",
                                                            "TCGGGACGTTGCCAAT-1_2",
                                                            "CGTTAGAAGAAAGCGA-1_2",
                                                            "ACTGTGAAGGTTGCCC-1_2",
                                                            "ATCCACCGTATGGGAC-1_2",
                                                            "CACAACAAGAAATCCA-1_2",
                                                            "ACTGATGGTACTCCCT-1_2",
                                                            "TGTAACGTCTGTCTCG-1_2",
                                                            "GTAGAAATCAAACCCA-1_2",
                                                            "ATGATCGAGGCGTTAG-1_2",
                                                            "TCTTCCTTCATGCGGC-1_2",
                                                            "CGCCAGACACCACTGG-1_2",
                                                            "AACAGGGCATACCGTA-1_2",
                                                            "ATGGAGGCAGAGGCTA-1_2",
                                                            "CGCATGGCATCGTGGC-1_2",
                                                            "GGATCTATCCTTATGT-1_2",
                                                            "GTGGTTACATGACGTT-1_2",
                                                            "GCCCAGAAGCTCTATG-1_2",
                                                            "AGCTTCCGTCCTTGTC-1_2",
                                                            "CAGATCATCATTGCTT-1_2",
                                                            "GGAGGTACAACTCGTA-1_2",
                                                            "GGTGGCTCAACCGACC-1_2",
                                                            "ATATCCTCATGGCACC-1_2",
                                                            "GAGTTTGAGATCACTC-1_3",
                                                            "GGCTTGGTCTAGACAC-1_3",
                                                            "GCCTGTTAGTCTAGAA-1_3",
                                                            "CACAGGCTCTTACTGT-1_3",
                                                            "GTTCGCTTCCCGTTCA-1_3",
                                                            "AGACAAACACGTACTA-1_3",
                                                            "TGGGATTTCGGCTGGT-1_3",
                                                            "TAACACGTCTGGCCAG-1_3",
                                                            "TCTTAGTTCGCTTGCT-1_3",
                                                            "AGGTAGGGTATGTGTC-1_3",
                                                            "TTCCAATTCAGACAAA-1_3",
                                                            "GTTTACTGTCGCGTCA-1_3",
                                                            "CACCGTTCAGAGTCTT-1_3",
                                                            "CCTGTTGTCCGCCTAT-1_3",
                                                            "GTTGCGGTCTTCTGTA-1_3",
                                                            "ATGATCGGTTCAGCTA-1_3",
                                                            "TCTACATGTCGCCACA-1_3",
                                                            "CGCATAAAGTTCCGTA-1_3",
                                                            "CCTCATGCATTGAAAG-1_3",
                                                            "CTGCTCAAGGCCTTGC-1_3",
                                                            "TGATTCTCAGTTCACA-1_3",
                                                            "ACGGAAGGTCGATTAC-1_3",
                                                            "ATCCATTAGTGCACTT-1_3",
                                                            "GAGTCATTCGCTCCTA-1_3",
                                                            "ACACCAAGTACTGACT-1_3",
                                                            "GTTGTCCGTCTACGTA-1_3",
                                                            "AAACGCTTCTATGTGG-1_3",
                                                            "CTCTCGAAGCATGCGA-1_3",
                                                            "TCTATCAAGCTTAAGA-1_3",
                                                            "ATGGGAGGTCGGCTAC-1_3",
                                                            "GTGCTTCTCAGCTGAT-1_3",
                                                            "AACCATGTCGAGTCTA-1_3",
                                                            "GGCGTCACATAACAGA-1_3",
                                                            "CGAAGGAAGGATGAGA-1_3",
                                                            "AGCGTCGCAAATACGA-1_3",
                                                            "TCGTGGGTCCCGGTAG-1_3",
                                                            "GCCGTGACAGTTCACA-1_3",
                                                            "CACATGAGTCCCGCAA-1_3",
                                                            "AAGGAATTCCGCGGAT-1_3",
                                                            "CCCTCAATCGACGAGA-1_3",
                                                            "GGCTTTCCAACACACT-1_3",
                                                            "TATCTTGAGATGGCGT-1_3",
                                                            "TCAGCAACAGCGACCT-1_3",
                                                            "GGTTGTACATCTTAGG-1_3",
                                                            "ATGGGTTTCGTAGCTA-1_3",
                                                            "TCAGTTTAGGCTCACC-1_3",
                                                            "CCCGGAAGTCTCTCAC-1_3",
                                                            "ATCGGCGCAGCAATTC-1_3",
                                                            "ATCCACCGTTCCAAAC-1_3",
                                                            "TTCGGTCAGACTCATC-1_3",
                                                            "CACAGATGTAAGGAGA-1_3",
                                                            "AGTAACCCAACTGAAA-1_3",
                                                            "CGCATAAGTTACGCCG-1_3",
                                                            "GCTCAAAAGCGTGCCT-1_3",
                                                            "CTGGACGAGGTTACAA-1_3",
                                                            "TTGTGGACAAGATGGC-1_3",
                                                            "TATTGCTAGGTGGGTT-1_3",
                                                            "GTATTGGGTCGCATGC-1_3",
                                                            "AGATCCAAGATCCCGC-1_3",
                                                            "TTCTAACTCGATCCAA-1_3",
                                                            "CTGCGAGAGCGTCAAG-1_3",
                                                            "CTTTCGGGTCGTTCAA-1_3",
                                                            "CGAGTGCTCCCTTCCC-1_3",
                                                            "GGCTTTCAGTTTAGGA-1_3",
                                                            "GTTGCGGGTCTCAGAT-1_3",
                                                            "GCATGATAGTACCGGA-1_3",
                                                            "CCTCCAAGTGTTCCTC-1_3",
                                                            "CGAAGGATCCCAAGTA-1_3",
                                                            "ACTATTCGTAACAGTA-1_3",
                                                            "TGGAGAGGTTGCCAAT-1_3",
                                                            "CCCTTAGAGGAAGAAC-1_3",
                                                            "AAGGTAATCCTGTTGC-1_3",
                                                            "CACATGACAGGTATGG-1_3",
                                                            "TTAGGGTGTACTTGTG-1_3",
                                                            "CTGAGGCGTTGGAGGT-1_3",
                                                            "AATGCCATCAAACCCA-1_3",
                                                            "AAGTTCGTCTGCGTCT-1_3",
                                                            "GCGGATCGTCTACTGA-1_3",
                                                            "AGGGCTCTCTAGCCTC-1_3",
                                                            "GTGGAGACACTTGTGA-1_3",
                                                            "AATGAAGAGGGCTTCC-1_3",
                                                            "GCTGAATTCGATTTCT-1_3",
                                                            "CGTCCATTCCATTGCC-1_3",
                                                            "CATCGGGAGAAGTCTA-1_3",
                                                            "GACCCTTCAATACCCA-1_3",
                                                            "AAGATAGCACACAGCC-1_3",
                                                            "CTACAGACAATCCAGT-1_3",
                                                            "TTTACCAGTACTGTTG-1_3",
                                                            "AATGGCTCACCGTGCA-1_3",
                                                            "ACAGAAATCTTCGATT-1_3",
                                                            "TTTACCAAGACCAGAC-1_3",
                                                            "GGCACGTTCCTCGCAT-1_3",
                                                            "AAAGGTAGTTACGGAG-1_3",
                                                            "AGTAACCGTACCAGAG-1_3",
                                                            "ACAGCCGAGTAATTGG-1_3",
                                                            "CATCAAGCACCGGTCA-1_3",
                                                            "TACGTCCGTACTGCGC-1_3",
                                                            "GAACGTTAGGCGCTTC-1_3",
                                                            "ATGAAAGCATCAGTGT-1_3",
                                                            "TCAGTGAAGCAAACAT-1_3",
                                                            "CTACAGATCATCTACT-1_3",
                                                            "ATTCTACGTGAGTAAT-1_3",
                                                            "GGGTTATGTTCCTAGA-1_3",
                                                            "CATTCATGTAACTTCG-1_3",
                                                            "CATACAGTCTACGGGC-1_3",
                                                            "GTGAGCCCACGCCAGT-1_3",
                                                            "GAATAGATCAGAGCGA-1_3",
                                                            "CCGGTAGTCTGTTCAT-1_3",
                                                            "AGGCTGCTCGATCCCT-1_3",
                                                            "ATTCTACGTATCAAGA-1_3",
                                                            "CCATAAGTCAGTGTCA-1_3",
                                                            "CTCACTGCACCGTCTT-1_3",
                                                            "CCTTCAGAGTGGCGAT-1_3",
                                                            "GATTTCTAGTTCTACG-1_3",
                                                            "TTCAGGATCAGTCATG-1_3",
                                                            "GAGTCATTCTCAACCC-1_3",
                                                            "TGAGGAGGTTGCAACT-1_3",
                                                            "TGGGCGTAGCAGGTCA-1_3",
                                                            "AATAGAGGTCAACATC-1_3",
                                                            "ACCGTTCTCAAAGACA-1_3",
                                                            "TCGATTTGTTGTTGTG-1_3",
                                                            "GGGATCCGTCCAAAGG-1_3",
                                                            "TAACCAGGTGGCTAGA-1_3",
                                                            "TACTTGTCACATATGC-1_3",
                                                            "CCCTGATAGTTCGGTT-1_3",
                                                            "TGATTCTGTCTCAGAT-1_3",
                                                            "CTCCGATAGGCCTTCG-1_3",
                                                            "ATACCTTCAGAAATCA-1_3",
                                                            "ACTTAGGAGCCTGGAA-1_3",
                                                            "AGTTCGAAGCAGTAAT-1_3",
                                                            "AATCGTGTCTGTCAGA-1_4",
                                                            "GTTTGGATCCCTTCCC-1_4",
                                                            "GTGCACGCATTCGGGC-1_4",
                                                            "AACAAAGTCCAATCCC-1_4",
                                                            "ACTGCAACATGCTGCG-1_4",
                                                            "ATGACCACAGTGTGGA-1_4",
                                                            "AACAGGGGTACCGTGC-1_4",
                                                            "TGGGATTTCGTCGATA-1_4",
                                                            "GTCGTTCTCCTCACCA-1_4",
                                                            "TCTCAGCAGTCCCGAC-1_4",
                                                            "TCACTCGCACTCCCTA-1_4",
                                                            "TTGTTTGCACCTAAAC-1_4",
                                                            "GATGAGGCATTGGATC-1_4",
                                                            "GTTACAGTCTTCTTCC-1_4",
                                                            "TGCTCCAGTACGACTT-1_4",
                                                            "CTCCACACATCTCATT-1_4",
                                                            "TATACCTAGAGAGCGG-1_4",
                                                            "CCGCAAGCAATCACGT-1_4",
                                                            "TCCATCGAGAATCGCG-1_4",
                                                            "GTTCGCTGTCTAGATC-1_4",
                                                            "CAACCTCTCCGATCGG-1_4",
                                                            "TCAGGTATCGTCGCTT-1_4",
                                                            "GTGCACGGTCGTAATC-1_4",
                                                            "CTGAATGGTAGCTTAC-1_4",
                                                            "TACTTACCAATAACGA-1_4",
                                                            "TCGACGGAGCTGCCTG-1_4",
                                                            "TCTACATAGGAATGTT-1_4",
                                                            "TGTCAGAAGATTGAGT-1_4",
                                                            "TGAATCGGTTGCCATA-1_4",
                                                            "GAATCACGTCTCGCGA-1_4",
                                                            "ACACGCGCAATTTCTC-1_4",
                                                            "CTCAAGAGTGAGGCAT-1_4",
                                                            "GCTGAATGTAAGGCTG-1_4",
                                                            "CATCGGGCATGACGGA-1_4",
                                                            "TCAGTTTGTTGCATAC-1_4",
                                                            "AGTGACTTCAAGGTGG-1_4",
                                                            "TCCGTGTAGTAAAGCT-1_4",
                                                            "TATTGGGCAAGACGGT-1_4",
                                                            "TACAACGGTCGAGTGA-1_4",
                                                            "CTTCAATTCGGTTGTA-1_4",
                                                            "CCACCATTCGGAACTT-1_4",
                                                            "TGGAGGATCATCTGTT-1_4",
                                                            "GGATCTAGTGCCCAGT-1_4",
                                                            "TCCTTTCAGACAGCGT-1_4",
                                                            "CAACGGCGTCTTGAAC-1_4",
                                                            "CAGCACGAGGAAAGGT-1_4",
                                                            "ATCAGGTTCTCTTAAC-1_4",
                                                            "AGCTCAATCACGGTCG-1_4",
                                                            "ACACGCGGTGGCGTAA-1_4",
                                                            "CTGCCTAGTCGAGCAA-1_4",
                                                            "TTCTGTAGTAGAATAC-1_4",
                                                            "ATGCATGAGTTGCCTA-1_4",
                                                            "GTGAGTTGTTTGAACC-1_4",
                                                            "CTAGGTAAGTAAGCAT-1_4",
                                                            "AACAAAGTCGATACAC-1_4",
                                                            "ATTTACCCAAGAGGCT-1_4",
                                                            "CTACATTAGGACGCTA-1_4",
                                                            "TAAGCCATCAAGCTGT-1_4",
                                                            "TGCTCCATCCATTTGT-1_4",
                                                            "GTCGTAAGTGTGTCCG-1_4",
                                                            "AGGTAGGCAGTTGTCA-1_4",
                                                            "GTGGGAAGTAGGCTCC-1_4",
                                                            "GTCTGTCGTGTTACAC-1_4",
                                                            "CGGGTCAAGAGCCTGA-1_4",
                                                            "TGCATCCCATGGAGAC-1_4",
                                                            "CCTCCAAAGGGATCTG-1_4",
                                                            "GGTAACTAGTTGGAAT-1_4",
                                                            "TATCTGTCAAAGCGTG-1_4",
                                                            "CTGTCGTAGTGCACCC-1_4",
                                                            "CTCGAGGCAACGAGGT-1_4",
                                                            "TGAATGCCAATGCAAA-1_4",
                                                            "GTTAGTGAGGGAGAAT-1_4",
                                                            "CATTGCCCAATTAGGA-1_4",
                                                            "GCAGGCTAGCACCCAC-1_4",
                                                            "CAAGGGAAGATGGCAC-1_4",
                                                            "CATGAGTAGGTCGAGT-1_4",
                                                            "TCACTATGTATGGTTC-1_4",
                                                            "GATTCTTCAAGACAAT-1_4",
                                                            "AACAAGAGTCACCGCA-1_4",
                                                            "GGGCCATCATTCTGTT-1_4",
                                                            "CATGAGTGTGCACGCT-1_4",
                                                            "ACAGGGATCGGTAAGG-1_4",
                                                            "ATTCCTAGTACCCACG-1_4",
                                                            "GACACGCAGTTGTAAG-1_4",
                                                            "GACCTTCCAGTAGAAT-1_4",
                                                            "GGTCACGAGCCTGAAG-1_4",
                                                            "AAACCCAAGGTCGTCC-1_4",
                                                            "GTTGCGGAGCGCTGAA-1_4",
                                                            "GCTTGGGAGTAAGGGA-1_4",
                                                            "TGATTCTAGACTGAGC-1_4",
                                                            "TGCAGGCAGTCTTGGT-1_4",
                                                            "CCGGTAGCAGTGGTGA-1_4",
                                                            "TGTTCTAAGAGGGCGA-1_4",
                                                            "GAGAAATGTCACTTAG-1_4",
                                                            "AGAGAGCTCGGCTATA-1_4",
                                                            "CTTTCAAGTGCCCAGT-1_4",
                                                            "TGCAGTAGTCTTCCGT-1_4",
                                                            "CTCCAACTCACGAGGA-1_4",
                                                            "TTCATGTGTCGTGGTC-1_4",
                                                            "GTCCACTAGCGATGAC-1_4",
                                                            "AACTTCTCACACTGGC-1_4",
                                                            "CCTCACATCTGAGTCA-1_4",
                                                            "CGATCGGAGTTGGGAC-1_4",
                                                            "GACCCAGTCGTACCTC-1_4",
                                                            "AGAGAATGTTACGATC-1_4",
                                                            "TTGGATGAGAGGCCAT-1_4",
                                                            "GTCATCCTCGAGTGGA-1_4",
                                                            "CACGTTCCATATGGCT-1_4",
                                                            "TGTGCGGCATTCTGTT-1_4",
                                                            "CTAACTTAGACAACAT-1_4",
                                                            "GTGTTAGGTCGCATGC-1_4",
                                                            "CTTGAGACAATCACGT-1_4",
                                                            "AAAGTCCTCTCTATGT-1_4",
                                                            "AAGTTCGAGATGGTAT-1_4",
                                                            "ACGTCCTAGCACCGAA-1_4",
                                                            "CGTAATGGTGACATCT-1_4",
                                                            "GAGACTTCAAAGAGTT-1_4",
                                                            "GATCAGTTCCTAGCGG-1_4",
                                                            "TTCCTAATCTCGAACA-1_4",
                                                            "TTGGTTTGTCCTTTGC-1_4",
                                                            "GCCTGTTAGCGTGCCT-1_4",
                                                            "AGCCAATTCGACGAGA-1_4",
                                                            "GTGGAGATCAAACTGC-1_4",
                                                            "CTGTCGTGTGTAGTGG-1_4",
                                                            "GGCAGTCGTAGCTTTG-1_4",
                                                            "AGGGCTCAGGACATCG-1_4",
                                                            "GCGATCGGTCTGTTAG-1_4",
                                                            "CCTCATGGTATCACGT-1_4",
                                                            "TAATTCCCATTCTCCG-1_4",
                                                            "TCCTGCATCTACTGCC-1_4",
                                                            "GAGCTGCCACCTGAAT-1_4",
                                                            "AGTAACCTCGAGTCTA-1_4",
                                                            "CCATAAGCAGCGGTTC-1_4",
                                                            "TCATGGAGTTTGCAGT-1_4",
                                                            "TTACTGTAGCCTCTCT-1_4",
                                                            "GGTGGCTTCCTTCAGC-1_4",
                                                            "GCGGATCTCCCGTAAA-1_4",
                                                            "CATCCGTAGTTGGCGA-1_4",
                                                            "CGATCGGAGCCGCTTG-1_4",
                                                            "TTTCAGTCAGGAATCG-1_4",
                                                            "TCCCAGTCACGCTGAC-1_4",
                                                            "GCATTAGAGGCAGTCA-1_4",
                                                            "TTTACCATCGCACTCT-1_4",
                                                            "GTTATGGGTCTCAGAT-1_4",
                                                            "TTTACCAAGCAGTAAT-1_4",
                                                            "TGTCAGAGTTAAACCC-1_4",
                                                            "CATCGGGTCTAACACG-1_4",
                                                            "TAGACTGCATTGCAAC-1_4",
                                                            "ATGCGATAGGAACTAT-1_4",
                                                            "AGGGCCTAGGTAGACC-1_4",
                                                            "AGTGACTTCAAGAATG-1_4",
                                                            "CAGAGCCCAGCTCATA-1_4",
                                                            "CCCATTGAGTCGAGGT-1_4",
                                                            "TCCACCAAGCGAGGAG-1_4",
                                                            "TACAGGTGTGATTCTG-1_4",
                                                            "CATGCCTTCCTGGCTT-1_4",
                                                            "ATATCCTTCCTAAGTG-1_4",
                                                            "AAGTTCGGTGTGATGG-1_4",
                                                            "GAGAGGTCAGGACGAT-1_4",
                                                            "ATTATCCAGCAATTCC-1_4",
                                                            "TTCGCTGCAAGTGTCT-1_4",
                                                            "AATGCCACAACACACT-1_4",
                                                            "AGACCCGGTGTTGAGG-1_4",
                                                            "ATATCCTTCTCCCATG-1_4",
                                                            "TCCACCAGTATGGGAC-1_4",
                                                            "AGTAACCGTGCCTAAT-1_4",
                                                            "GATCGTAAGCGTTACT-1_4",
                                                            "ATAGGCTGTCGTATTG-1_4",
                                                            "GTTATGGCAGTAGTTC-1_4",
                                                            "CGTAGTATCCAAGAGG-1_4",
                                                            "AACCACAGTATATGGA-1_4",
                                                            "TAAGTCGTCTGCGATA-1_4",
                                                            "GGACGTCAGACGTCGA-1_4",
                                                            "TCATATCTCCAATCCC-1_4",
                                                            "TGACAGTTCGGTCTAA-1_4",
                                                            "TCATGTTCAAACACGG-1_4",
                                                            "CCGATGGAGGCTAACG-1_4",
                                                            "ACCACAATCTCTCGCA-1_4",
                                                            "ATGGAGGGTCCATAGT-1_4",
                                                            "CTCCAACCATCAGCTA-1_4",
                                                            "TTGTTGTAGGGCAATC-1_4",
                                                            "CCTCAACCAGTCGGTC-1_4",
                                                            "AGTTAGCTCTATCACT-1_4",
                                                            "TCTTGCGAGCCAGACA-1_4",
                                                            "GCGTGCACATGACTAC-1_4",
                                                            "TTCCTAACAGTTCACA-1_4",
                                                            "TGAGGTTGTACTTGTG-1_4",
                                                            "CGTCAAAAGAGCACTG-1_4",
                                                            "TAGAGTCCAGGGTTGA-1_4",
                                                            "GAGTGTTAGAAGAACG-1_4",
                                                            "GCCAGGTTCGCCGAGT-1_4",
                                                            "TGTTCTACATCGAAGG-1_4",
                                                            "GGGTTTATCGCTTGCT-1_4",
                                                            "CTGAGCGTCTGCTCTG-1_4",
                                                            "GATTTCTCAGGTCCGT-1_4",
                                                            "CATTGTTGTGAATTGA-1_4",
                                                            "CCGGACAGTAACTGCT-1_4",
                                                            "GTGGAGAAGAGGGCGA-1_4",
                                                            "ATCATTCCAAGAGGCT-1_4",
                                                            "ATGGAGGAGTCATCGT-1_4",
                                                            "TACTTCACATCTTTCA-1_4",
                                                            "GGCTTTCGTTGCCGCA-1_4",
                                                            "ACCAACAGTAGCTTTG-1_4",
                                                            "GAAATGATCCGTAGTA-1_4",
                                                            "TCCTCGATCCGTATAG-1_4",
                                                            "TCCTGCAGTGATTAGA-1_4",
                                                            "CTCCGATAGGGATCAC-1_4",
                                                            "TTAGGCAAGCAAGTGC-1_4",
                                                            "CCGGGTAAGGTTCATC-1_4",
                                                            "ACAGCCGTCCTCTCTT-1_4",
                                                            "AGTTAGCGTGGAATGC-1_4",
                                                            "TCATATCCAAGTATAG-1_4",
                                                            "ATCGGCGGTGAGTTTC-1_4",
                                                            "AGTCATGTCGCCAATA-1_4",
                                                            "TCCGAAAAGGGCTGAT-1_4",
                                                            "TCCTAATGTACCTTCC-1_4",
                                                            "CGCATGGAGTAAGCAT-1_4",
                                                            "TCGGATAAGAGTACCG-1_4",
                                                            "CTATAGGGTATCCCTC-1_4",
                                                            "GCAACATGTCTCTCAC-1_4",
                                                            "CAAAGAACAGAAATCA-1_4",
                                                            "AACCCAAAGCAAGTGC-1_4",
                                                            "CACATGACACATATGC-1_4",
                                                            "GTAAGTCAGCAGAAAG-1_4",
                                                            "GTGGGAACACAACGTT-1_4",
                                                            "TTCATGTGTACGTGAG-1_4",
                                                            "ACTATGGAGCTACGTT-1_4",
                                                            "AATGCCATCTACACTT-1_4",
                                                            "TGACCCTTCGGCCCAA-1_4",
                                                            "TGCAGATCAAAGAGTT-1_4",
                                                            "GGGATCCAGTAAATGC-1_4",
                                                            "GTAAGTCCACAACGAG-1_4",
                                                            "AACGTCACAAGATGGC-1_4",
                                                            "CTCCTCCCAAGGCGTA-1_4",
                                                            "CGACAGCCATACAGAA-1_4",
                                                            "ATCCCTGGTTACACAC-1_4",
                                                            "ACCTGTCCATCTGTTT-1_4",
                                                            "TTCACGCGTCGCTCGA-1_4",
                                                            "TGTTGGATCATCACTT-1_4",
                                                            "ATCGGCGAGGAGAATG-1_4",
                                                            "CCGGGTATCTACACAG-1_4"),invert=T)
# save RDS file
saveRDS(seurat.obj.combined,file = "snRNA_seq_injury/results/SCT.CCA/1.data input & merge/goat_ON injury snRNA_SCT.CCA after delete outlier.rds")
