library(Seurat)
library(ggplot2)
library(future)
library(dplyr)

# snRNA-seq data input 
control1 <- Read10X("2.1 Exp Matrix/1OD3/filtered_feature_bc_matrix/")
control2 <- Read10X("2.1 Exp Matrix/3OD3/filtered_feature_bc_matrix/")
injury1 <- Read10X("2.1 Exp Matrix/2OS3/filtered_feature_bc_matrix/")
injury2 <- Read10X("2.1 Exp Matrix/3OS3/filtered_feature_bc_matrix/")
seurat.list<-list(control1=control1,control2=control2,injury1=injury1,injury2=injury2)


# crate seurat object
for (i in 1:length(seurat.list)) {
  seurat.list[[i]] <- CreateSeuratObject(seurat.list[[i]],
                                         project = names(seurat.list)[i], 
                                         min.cells = 3,
                                         min.features = 200,
  )
}


# quality control
dir.create("results/QC",recursive = T)
## QC
for (i in 1:length(seurat.list)) {
  VlnPlot(seurat.list[[i]], features = c("nFeature_RNA", "nCount_RNA"), ncol = 2,pt.size = 0)
  ggsave(filename = paste0("results/QC/QC-VlnPlot_",names(seurat.list)[i],".pdf"),width = 6,height = 4.5)
  a <- seurat.list[[i]]@meta.data
  ggplot(data = a,aes(x = a$nCount_RNA))+geom_density(fill="pink")+xlim(c(0,30000))
  ggsave(filename = paste0("results/QC/QC-nCount.density_",names(seurat.list)[i],".pdf"),width = 6,height = 4.5)
  ggplot(data = a,aes(x = a$nFeature_RNA))+geom_density(fill="pink")+xlim(c(0,10000))
  ggsave(filename = paste0("results/QC/QC-nFeature.density_",names(seurat.list)[i],".pdf"),width = 6,height = 4.5)
}


# filter threshold: Feature_RNA > 300 & nFeature_RNA < quantile(seurat_sample, 0.975)
## control1
cat(names(seurat.list)[1],": Before filter ",nrow(seurat.list[[1]]@meta.data),"cells\n") #Before filter : 8940 cells
seurat.list[[1]] <- subset(seurat.list[[1]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 4234)
cat(names(seurat.list)[1],": After filter ",nrow(seurat.list[[1]]@meta.data),"cells\n") #Before filter : 8714 cells

## control2
cat(names(seurat.list)[2],": Before filter ",nrow(seurat.list[[2]]@meta.data),"cells\n") #Before filter : 6877 cells
seurat.list[[2]] <- subset(seurat.list[[2]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 5091)
cat(names(seurat.list)[2],": After filter ",nrow(seurat.list[[2]]@meta.data),"cells\n") #Before filter : 6736 cells

## injury1
cat(names(seurat.list)[3],": Before filter ",nrow(seurat.list[[3]]@meta.data),"cells\n") #Before filter : 9427 cells
seurat.list[[3]] <- subset(seurat.list[[3]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 4778)
cat(names(seurat.list)[3],": After filter ",nrow(seurat.list[[3]]@meta.data),"cells\n") #Before filter : 9106 cells

## injury2
cat(names(seurat.list)[4],": Before filter ",nrow(seurat.list[[4]]@meta.data),"cells\n") #Before filter : 11987 cells
seurat.list[[4]] <- subset(seurat.list[[4]], 
                           subset = 
                             nFeature_RNA > 300 & 
                             nFeature_RNA < 4927)
cat(names(seurat.list)[4],": After filter ",nrow(seurat.list[[4]]@meta.data),"cells\n") #Before filter : 11684 cells


# SCTransform
seurat.list <- lapply(X = seurat.list, FUN = SCTransform )
features <- SelectIntegrationFeatures(object.list = seurat.list, nfeatures = 3000)
seurat.list <- PrepSCTIntegration(object.list = seurat.list, anchor.features = features)
seurat.obj.anchors <- FindIntegrationAnchors(object.list = seurat.list, normalization.method = "SCT", anchor.features = features)
seurat.obj.combined <- IntegrateData(anchorset = seurat.obj.anchors, normalization.method = "SCT")


# PCA
seurat.obj.combined <- RunPCA(seurat.obj.combined, verbose = FALSE)


# dir.create
dir.create("results/SCT.CCA")


# ElbowPlot
pdf(paste0("results/SCT.CCA/PCA-ElbowPlot.pdf"),width = 6,height = 5)
ElbowPlot(seurat.obj.combined,ndims = 50)
dev.off()


# choose dimention
dim.use <- 1:30


# clustering
seurat.obj.combined <- FindNeighbors(seurat.obj.combined, dims = dim.use,reduction = "pca")
seurat.obj.combined <- FindClusters(seurat.obj.combined, resolution = 0.6)


# UMAP reduction
seurat.obj.combined <- RunUMAP(seurat.obj.combined, reduction = "pca", dims = dim.use)

# RenameIdents
seurat.obj.combined <- RenameIdents(seurat.obj.combined,
                      "1"="Astrocyte",
                      "2"="MP",
                      "3"="Astrocyte",
                      "4"="Astrocyte",
                      "5"="Oligodendrocyte",
                      "6"="Fibroblast",
                      "7"="Astrocyte",
                      "8"="Fibroblast",
                      "9"="OPC",
                      "10"="VEC",
                      "11"="Fibroblast",
                      "12"="Undefined",
                      "13"="VEC",
                      "14"="Vascular Mural Cell",
                      "15"="Oligodendrocyte",
                      "16"="MP",
                      "17"="VEC",
                      "18"="Oligodendrocyte",
                      "19"="Astrocyte")
seurat.obj.combined$celltype_undefined <- Idents(seurat.obj.combined)

# drop outlier cells (Cells that are apparently far from the position of the cell population coordinates are discarded)
seurat.obj.combined <- subset(seurat.obj.combined=c("AATCGTGTCTGTCAGA-1_2",
                            "CAATGACTCTTTGGAG-1_1",
                            "AGACCCGCAAGGATGC-1_1",
                            "ATCGCCTCAGTTAGGG-1_1",
                            "TTCGGTCCACTGCATA-1_1",
                            "GTTTGGATCCCTTCCC-1_2",
                            "GAGTTTGAGATCACTC-1_2_1",
                            "GTGCACGCATTCGGGC-1_2",
                            "AACAAAGTCCAATCCC-1_2",
                            "ACTGCAACATGCTGCG-1_2",
                            "ATGACCACAGTGTGGA-1_2",
                            "AACAGGGGTACCGTGC-1_2",
                            "TGGGATTTCGTCGATA-1_2",
                            "GGCTTGGTCTAGACAC-1_2_1",
                            "GCCTGTTAGTCTAGAA-1_2_1",
                            "GTCGTTCTCCTCACCA-1_2",
                            "GCCATTCAGAATTCAG-1_1",
                            "TCTCAGCAGTCCCGAC-1_2",
                            "TCACTCGCACTCCCTA-1_2",
                            "TTGTTTGCACCTAAAC-1_2",
                            "GATGAGGCATTGGATC-1_2",
                            "GTTACAGTCTTCTTCC-1_2",
                            "TGCTCCAGTACGACTT-1_2",
                            "CACAGGCTCTTACTGT-1_2_1",
                            "GTTCGCTTCCCGTTCA-1_2_1",
                            "CTCCACACATCTCATT-1_2",
                            "TATACCTAGAGAGCGG-1_2",
                            "CCGCAAGCAATCACGT-1_2",
                            "TCCATCGAGAATCGCG-1_2",
                            "GTTCGCTGTCTAGATC-1_2",
                            "AGACAAACACGTACTA-1_2_1",
                            "CAACCTCTCCGATCGG-1_2",
                            "TCAGGTATCGTCGCTT-1_2",
                            "CGCATAAAGCTACTAC-1_1_1",
                            "GTGCACGGTCGTAATC-1_2",
                            "TGGGATTTCGGCTGGT-1_2_1",
                            "TAACACGTCTGGCCAG-1_2_1",
                            "CTGAATGGTAGCTTAC-1_2",
                            "TACTTACCAATAACGA-1_2",
                            "TCGACGGAGCTGCCTG-1_2",
                            "TCTACATAGGAATGTT-1_2",
                            "TGTCAGAAGATTGAGT-1_2",
                            "TGAATCGGTTGCCATA-1_2",
                            "GAATCACGTCTCGCGA-1_2",
                            "ACACGCGCAATTTCTC-1_2",
                            "CTCAAGAGTGAGGCAT-1_2",
                            "GCTGAATGTAAGGCTG-1_2",
                            "TCTTAGTTCGCTTGCT-1_2_1",
                            "AGGTAGGGTATGTGTC-1_2_1",
                            "CATCGGGCATGACGGA-1_2",
                            "CATCCCATCTGCGGCA-1_1_1",
                            "TCAGTTTGTTGCATAC-1_2",
                            "AGTGACTTCAAGGTGG-1_2",
                            "TCCGTGTAGTAAAGCT-1_2",
                            "TATTGGGCAAGACGGT-1_2",
                            "TTCCAATTCAGACAAA-1_2_1",
                            "GCAGCTGGTCACTGAT-1_1_1",
                            "TACAACGGTCGAGTGA-1_2",
                            "CTTCAATTCGGTTGTA-1_2",
                            "CCACCATTCGGAACTT-1_2",
                            "GTTTACTGTCGCGTCA-1_2_1",
                            "TGGAGGATCATCTGTT-1_2",
                            "GGATCTAGTGCCCAGT-1_2",
                            "TCCTTTCAGACAGCGT-1_2",
                            "CAACGGCGTCTTGAAC-1_2",
                            "CAGCACGAGGAAAGGT-1_2",
                            "GAGTTGTAGGTTTACC-1_1",
                            "CACCGTTCAGAGTCTT-1_2_1",
                            "CCTGTTGTCCGCCTAT-1_2_1",
                            "GTTGCGGTCTTCTGTA-1_2_1",
                            "ATCAGGTTCTCTTAAC-1_2",
                            "AGACACTTCCGCGATG-1_1",
                            "ATGATCGGTTCAGCTA-1_2_1",
                            "TCTACATGTCGCCACA-1_2_1",
                            "CCGGGTAAGGTGCCAA-1_1_1",
                            "TTCCAATAGCTTTCCC-1_1_1",
                            "AGACTCATCAAGGCTT-1_1_1",
                            "AGCTCAATCACGGTCG-1_2",
                            "TTCCTTCAGTGCTCGC-1_1_1",
                            "CCTCTCCTCGAGCACC-1_1",
                            "AAAGGGCTCGAGATGG-1_1_1",
                            "CATCGGGCAGAAATTG-1_1",
                            "TCATCCGGTGTCTCCT-1_1_1",
                            "GGCAGTCGTGTGTCGC-1_1_1",
                            "CATTGAGTCGTCCATC-1_1",
                            "GCACGTGCAGGTTTAC-1_1",
                            "TGTCCCAAGGCTATCT-1_1",
                            "ACACGCGGTGGCGTAA-1_2",
                            "AATGCCACAAGGTCTT-1_1",
                            "CGCATAAAGTTCCGTA-1_2_1",
                            "CTGCCTAGTCGAGCAA-1_2",
                            "GTCATGACACTATCGA-1_1",
                            "TGCACGGGTGCTCTTC-1_1",
                            "TGTGCGGAGACATCCT-1_1_1",
                            "AACGGGAAGTTGAATG-1_1_1",
                            "CAAGACTAGATCCTAC-1_1",
                            "TTCTGTAGTAGAATAC-1_2",
                            "CCCTAACGTAGAGGAA-1_1_1",
                            "TGTAGACCAGAGCCCT-1_1_1",
                            "CTCAAGACAGACCAAG-1_1_1",
                            "TCGAACACAGCAGAAC-1_1_1",
                            "ACCTACCGTCCAGAAG-1_1",
                            "ATGCATGAGTTGCCTA-1_2",
                            "CGGGACTCAACCGATT-1_1_1",
                            "TTCTTCCAGCTAATCC-1_1_1",
                            "AGTTAGCTCTGACAGT-1_1_1",
                            "CTTCTCTGTTGGAGAC-1_1_1",
                            "GTGAGTTGTTTGAACC-1_2",
                            "TCTCTGGCACGCACCA-1_1_1",
                            "GGGCTACGTAATCAGA-1_1_1",
                            "TACTTGTAGAGGGTGG-1_1",
                            "CTAGGTAAGTAAGCAT-1_2",
                            "AACGGGATCAGTAGGG-1_1_1",
                            "ACATCCCGTTCGTGCG-1_1_1",
                            "CGTGTCTCAGGTTCCG-1_1_1",
                            "GGCTTGGCAAGTCCAT-1_1_1",
                            "AACAAAGTCGATACAC-1_2",
                            "GAAGCGAGTCGAGTGA-1_1_1",
                            "AATCACGAGTTCCGTA-1_1_1",
                            "ATTTACCCAAGAGGCT-1_2",
                            "CCTCATGCATTGAAAG-1_2_1",
                            "GACAGCCCACACAGAG-1_1_1",
                            "ATTCAGGCAACATACC-1_1",
                            "GTAGAGGCACAATGAA-1_1_1",
                            "CACTAAGTCCCGTTCA-1_1_1",
                            "GAGGCCTTCTTCGGTC-1_1_1",
                            "TCGGTCTTCCGTACGG-1_1_1",
                            "CTACATTAGGACGCTA-1_2",
                            "CTTCAATTCAATGTCG-1_1_1",
                            "ATTGGGTAGGTTTGAA-1_1_1",
                            "ACCAACAGTTCTCTCG-1_1_1",
                            "CGCATAACACACGTGC-1_1_1",
                            "TAACCAGAGACCAGCA-1_1_1",
                            "TATATCCCATTCTCCG-1_1_1",
                            "CCGATGGCATGGAATA-1_1_1",
                            "TAAGCCATCAAGCTGT-1_2",
                            "ACCTGTCGTACGAAAT-1_1_1",
                            "ACTTTCACATTGAGCT-1_1_1",
                            "CTCCCTCGTGGACAGT-1_1",
                            "ATCCACCTCCACTTTA-1_1_1",
                            "TGCTCCATCCATTTGT-1_2",
                            "CCCATTGGTCTTGCTC-1_1_1",
                            "CTGCTCAAGGCCTTGC-1_2_1",
                            "GTCATGATCGTCAGAT-1_1_1",
                            "CTGTACCAGTTCGCAT-1_1_1",
                            "TGATTCTCAGTTCACA-1_2_1",
                            "AGGTAGGGTAGCCAGA-1_1_1",
                            "GTCGTAAGTGTGTCCG-1_2",
                            "TCCTGCAAGTGAGCCA-1_1_1",
                            "ACGATGTAGGATCATA-1_1",
                            "ATTCCATTCGATTGAC-1_1_1",
                            "GTTATGGAGTGAGTTA-1_1",
                            "GATTCGAGTGCTCTCT-1_1",
                            "AGAAATGCACATTCTT-1_1",
                            "CTACCTGGTCACTTCC-1_1",
                            "GGCACGTAGCTAGTTC-1_1_1",
                            "TCCGGGAAGCTAGCCC-1_1_1",
                            "TACCGGGTCCGGCAGT-1_1",
                            "AATCACGCAGATCCAT-1_1_1",
                            "GAACACTAGCTGGCCT-1_1",
                            "AGAAGTAAGGACGCTA-1_1_1",
                            "ACGGAAGGTCGATTAC-1_2_1",
                            "CCAAGCGGTCCTTGTC-1_1_1",
                            "AGGTAGGCAGTTGTCA-1_2",
                            "GTGGGAAGTAGGCTCC-1_2",
                            "GTCTGTCGTGTTACAC-1_2",
                            "AGATCGTCACTCGATA-1_1_1",
                            "ATCCGTCGTGGCCCAT-1_1_1",
                            "TCATTCAAGTCGGGAT-1_1",
                            "TGGTACACACTTCAGA-1_1",
                            "AAAGGTATCGAAGGAC-1_1_1",
                            "ATCCATTAGTGCACTT-1_2_1",
                            "CTGTAGAGTACTAAGA-1_1_1",
                            "CGGGTCAAGAGCCTGA-1_2",
                            "CAGATTGGTGTCCATA-1_1_1",
                            "TGCATCCCATGGAGAC-1_2",
                            "ATGGATCGTTCCGGTG-1_1_1",
                            "TCCGATCAGGCTAGCA-1_1_1",
                            "CCTCCAAAGGGATCTG-1_2",
                            "GGTAACTAGTTGGAAT-1_2",
                            "TATCTGTCAAAGCGTG-1_2",
                            "GAGTCATTCGCTCCTA-1_2_1",
                            "CTGTCGTAGTGCACCC-1_2",
                            "CTCGAGGCAACGAGGT-1_2",
                            "TGAATGCCAATGCAAA-1_2",
                            "ATGAGTCGTACGATGG-1_1_1",
                            "GTTAGTGAGGGAGAAT-1_2",
                            "CATTGCCCAATTAGGA-1_2",
                            "ACACCAAGTACTGACT-1_2_1",
                            "CGAGTTACAATACCCA-1_1",
                            "GCAGGCTAGCACCCAC-1_2",
                            "CTCGAGGTCGAAGAAT-1_1_1",
                            "CAAGGGAAGATGGCAC-1_2",
                            "GTTGAACAGGACTGGT-1_1_1",
                            "GTAGAAAGTGGTCTGC-1_1_1",
                            "GCCCGAACACCTGTCT-1_1",
                            "CATGAGTAGGTCGAGT-1_2",
                            "CTCATCGAGGGAGGAC-1_1_1",
                            "GGTTGTAAGGTACATA-1_1_1",
                            "TCCCACAGTCGCAACC-1_1_1",
                            "TCACTATGTATGGTTC-1_2",
                            "GATTCTTCAAGACAAT-1_2",
                            "AACAAGAGTCACCGCA-1_2",
                            "GTTGTCCGTCTACGTA-1_2_1",
                            "GGGCCATCATTCTGTT-1_2",
                            "ACGATGTGTGTCTTAG-1_1_1",
                            "AAACGCTTCTATGTGG-1_2_1",
                            "CATGAGTGTGCACGCT-1_2",
                            "ACAGGGATCGGTAAGG-1_2",
                            "ATTCCTAGTACCCACG-1_2",
                            "GACACGCAGTTGTAAG-1_2",
                            "ATCCATTAGCGGGTAT-1_1",
                            "TGATTCTTCCAGCTCT-1_1",
                            "CTCTCGAAGCATGCGA-1_2_1",
                            "TCTATCAAGCTTAAGA-1_2_1",
                            "GACCTTCCAGTAGAAT-1_2",
                            "ATGGGAGGTCGGCTAC-1_2_1",
                            "GTGCTTCTCAGCTGAT-1_2_1",
                            "GGTCACGAGCCTGAAG-1_2",
                            "AAACCCAAGGTCGTCC-1_2",
                            "GTTGCGGAGCGCTGAA-1_2",
                            "GCTTGGGAGTAAGGGA-1_2",
                            "TGATTCTAGACTGAGC-1_2",
                            "TGCAGGCAGTCTTGGT-1_2",
                            "AACCATGTCGAGTCTA-1_2_1",
                            "GACCCAGGTGGTCCCA-1_1_1",
                            "GGCGTCACATAACAGA-1_2_1",
                            "CGAAGGAAGGATGAGA-1_2_1",
                            "CCGGTAGCAGTGGTGA-1_2",
                            "CGTCAAAAGGCATGCA-1_1_1",
                            "TCCTTCTAGGGCTGAT-1_1_1",
                            "ATGACCAAGACTTAAG-1_1",
                            "TGTTCTAAGAGGGCGA-1_2",
                            "GAGAAATGTCACTTAG-1_2",
                            "AGAGAGCTCGGCTATA-1_2",
                            "CTTTCAAGTGCCCAGT-1_2",
                            "TGCAGTAGTCTTCCGT-1_2",
                            "CTCCAACTCACGAGGA-1_2",
                            "TTATTGCCACATACTG-1_1",
                            "TTCATGTGTCGTGGTC-1_2",
                            "AGCGTCGCAAATACGA-1_2_1",
                            "ACCTACCAGTAACGAT-1_1_1",
                            "GTCCACTAGCGATGAC-1_2",
                            "AACTTCTCACACTGGC-1_2",
                            "CCTCACATCTGAGTCA-1_2",
                            "TCGTGGGTCCCGGTAG-1_2_1",
                            "CGATCGGAGTTGGGAC-1_2",
                            "GCCGTGACAGTTCACA-1_2_1",
                            "GACCCAGTCGTACCTC-1_2",
                            "CACGTGGGTACGAAAT-1_1_1",
                            "GAGAAATAGGTCCTGC-1_1",
                            "TATCTGTCACAGAGAC-1_1",
                            "AGAGAATGTTACGATC-1_2",
                            "TCTTAGTAGTGCCGAA-1_1_1",
                            "CACATGAGTCCCGCAA-1_2_1",
                            "TTGGATGAGAGGCCAT-1_2",
                            "AAGGAATTCCGCGGAT-1_2_1",
                            "GACCCAGTCGATCCCT-1_1_1",
                            "GTCATCCTCGAGTGGA-1_2",
                            "CCCTCAATCGACGAGA-1_2_1",
                            "ACCACAATCCGTGTCT-1_1",
                            "GGTCTGGCACTGCATA-1_1_1",
                            "CACGTTCCATATGGCT-1_2",
                            "GGCTTTCCAACACACT-1_2_1",
                            "TGTGCGGCATTCTGTT-1_2",
                            "TATCTTGAGATGGCGT-1_2_1",
                            "TCAGCAACAGCGACCT-1_2_1",
                            "CTAACTTAGACAACAT-1_2",
                            "GGGTCTGTCTGAGAGG-1_1",
                            "GGTTGTACATCTTAGG-1_2_1",
                            "AGTGCCGTCTCCACTG-1_1",
                            "GTGTTAGGTCGCATGC-1_2",
                            "ATTTCTGGTAGAAACT-1_1_1",
                            "CTTGAGACAATCACGT-1_2",
                            "AAAGTCCTCTCTATGT-1_2",
                            "AAGTTCGAGATGGTAT-1_2",
                            "ACGTCCTAGCACCGAA-1_2",
                            "TGCATCCCAATAGGAT-1_1",
                            "CGTAATGGTGACATCT-1_2",
                            "ATGGGTTTCGTAGCTA-1_2_1",
                            "GAGACTTCAAAGAGTT-1_2",
                            "TCAGTTTAGGCTCACC-1_2_1",
                            "CCCGGAAGTCTCTCAC-1_2_1",
                            "ATCGGCGCAGCAATTC-1_2_1",
                            "ATCCACCGTTCCAAAC-1_2_1",
                            "GATCAGTTCCTAGCGG-1_2",
                            "TTCGGTCAGACTCATC-1_2_1",
                            "CACAGATGTAAGGAGA-1_2_1",
                            "AGTAACCCAACTGAAA-1_2_1",
                            "CGCATAAGTTACGCCG-1_2_1",
                            "GCTCAAAAGCGTGCCT-1_2_1",
                            "CTGGACGAGGTTACAA-1_2_1",
                            "TTCCTAATCTCGAACA-1_2",
                            "TTGTGGACAAGATGGC-1_2_1",
                            "ACTCCCACAACCAATC-1_1",
                            "TTGGTTTGTCCTTTGC-1_2",
                            "TATTGCTAGGTGGGTT-1_2_1",
                            "GCCTGTTAGCGTGCCT-1_2",
                            "AGCCAATTCGACGAGA-1_2",
                            "AACCAACTCCGGACTG-1_1_1",
                            "GTGGAGATCAAACTGC-1_2",
                            "CTGTCGTGTGTAGTGG-1_2",
                            "GGCAGTCGTAGCTTTG-1_2",
                            "AGGGCTCAGGACATCG-1_2",
                            "ATTCACTGTCTAATCG-1_1_1",
                            "GTATTGGGTCGCATGC-1_2_1",
                            "AAGCGAGAGGGAGATA-1_1",
                            "CCCAACTCACTGGATT-1_1",
                            "TCCACCAGTTTGTGGT-1_1_1",
                            "GCGATCGGTCTGTTAG-1_2",
                            "AGTGACTCATGACACT-1_1",
                            "GCCATGGAGTTGTACC-1_1",
                            "CCTCATGGTATCACGT-1_2",
                            "TAATTCCCATTCTCCG-1_2",
                            "AGATCCAAGATCCCGC-1_2_1",
                            "TCCTGCATCTACTGCC-1_2",
                            "GAGCTGCCACCTGAAT-1_2",
                            "AGTAACCTCGAGTCTA-1_2",
                            "CGAGAAGTCATCGACA-1_1",
                            "CCATAAGCAGCGGTTC-1_2",
                            "TCATGGAGTTTGCAGT-1_2",
                            "TTCTAACTCGATCCAA-1_2_1",
                            "TTACTGTAGCCTCTCT-1_2",
                            "CTGCGAGAGCGTCAAG-1_2_1",
                            "GGTGGCTTCCTTCAGC-1_2",
                            "CTTTCGGGTCGTTCAA-1_2_1",
                            "GCGGATCTCCCGTAAA-1_2",
                            "CATCCGTAGTTGGCGA-1_2",
                            "CGATCGGAGCCGCTTG-1_2",
                            "TTTCAGTCAGGAATCG-1_2",
                            "TCCCAGTCACGCTGAC-1_2",
                            "GCATTAGAGGCAGTCA-1_2",
                            "CGAGTGCTCCCTTCCC-1_2_1",
                            "GGCTTTCAGTTTAGGA-1_2_1",
                            "TTTACCATCGCACTCT-1_2",
                            "GTTATGGGTCTCAGAT-1_2",
                            "TCAATTCGTCATAAAG-1_1",
                            "TTTACCAAGCAGTAAT-1_2",
                            "TGTCAGAGTTAAACCC-1_2",
                            "CATCGGGTCTAACACG-1_2",
                            "GTTGCGGGTCTCAGAT-1_2_1",
                            "TACGGGCGTGAATTGA-1_1",
                            "GCATGATAGTACCGGA-1_2_1",
                            "CCTCCAAGTGTTCCTC-1_2_1",
                            "TAGACTGCATTGCAAC-1_2",
                            "GCAGCTGAGACCATAA-1_1",
                            "CGAAGGATCCCAAGTA-1_2_1",
                            "ATGCGATAGGAACTAT-1_2",
                            "ACTATTCGTAACAGTA-1_2_1",
                            "AGGGCCTAGGTAGACC-1_2",
                            "AGTGACTTCAAGAATG-1_2",
                            "ACAACCATCGGAAACG-1_1",
                            "CAGAGCCCAGCTCATA-1_2",
                            "CCCATTGAGTCGAGGT-1_2",
                            "TGGAGAGGTTGCCAAT-1_2_1",
                            "CCGAACGTCTACTGCC-1_1",
                            "GCATTAGTCTACGCAA-1_1",
                            "AGTGATCTCAGGGATG-1_1",
                            "TCCACCAAGCGAGGAG-1_2",
                            "TCGGGACTCGAGTCTA-1_1_1",
                            "TACAGGTGTGATTCTG-1_2",
                            "TTCAGGATCGTCGACG-1_1",
                            "GTAGAAATCCACTGGG-1_1_1",
                            "CATGCCTTCCTGGCTT-1_2",
                            "CCCTTAGAGGAAGAAC-1_2_1",
                            "AAGGTAATCCTGTTGC-1_2_1",
                            "AACCAACGTGCTAGCC-1_1",
                            "ATATCCTTCCTAAGTG-1_2",
                            "AAGTTCGGTGTGATGG-1_2",
                            "CACATGACAGGTATGG-1_2_1",
                            "GAGAGGTCAGGACGAT-1_2",
                            "AAGTACCGTACAGTCT-1_1",
                            "TTAGGGTGTACTTGTG-1_2_1",
                            "CTGAGGCGTTGGAGGT-1_2_1",
                            "ATTATCCAGCAATTCC-1_2",
                            "AATGCCATCAAACCCA-1_2_1",
                            "GAAACCTAGCGAATGC-1_1",
                            "TTCGCTGCAAGTGTCT-1_2",
                            "AAGTTCGTCTGCGTCT-1_2_1",
                            "AATGCCACAACACACT-1_2",
                            "AGACCCGGTGTTGAGG-1_2",
                            "GCGGATCGTCTACTGA-1_2_1",
                            "AGGGCTCTCTAGCCTC-1_2_1",
                            "ATATCCTTCTCCCATG-1_2",
                            "TCCACCAGTATGGGAC-1_2",
                            "AGTAACCGTGCCTAAT-1_2",
                            "GTGGAGACACTTGTGA-1_2_1",
                            "GATCGTAAGCGTTACT-1_2",
                            "ATAGGCTGTCGTATTG-1_2",
                            "GTTATGGCAGTAGTTC-1_2",
                            "CGTAGTATCCAAGAGG-1_2",
                            "AACCACAGTATATGGA-1_2",
                            "AATGAAGAGGGCTTCC-1_2_1",
                            "TAAGTCGTCTGCGATA-1_2",
                            "ACCCAAAAGAATACAC-1_1_1",
                            "GCTGAATTCGATTTCT-1_2_1",
                            "CGTCCATTCCATTGCC-1_2_1",
                            "CATCGGGAGAAGTCTA-1_2_1",
                            "GGACGTCAGACGTCGA-1_2",
                            "TCATATCTCCAATCCC-1_2",
                            "GACCCTTCAATACCCA-1_2_1",
                            "AAGATAGCACACAGCC-1_2_1",
                            "TGACAGTTCGGTCTAA-1_2",
                            "CTACAGACAATCCAGT-1_2_1",
                            "TTTACCAGTACTGTTG-1_2_1",
                            "AATGGCTCACCGTGCA-1_2_1",
                            "TCATGTTCAAACACGG-1_2",
                            "ACAGAAATCTTCGATT-1_2_1",
                            "TTTACCAAGACCAGAC-1_2_1",
                            "CCGATGGAGGCTAACG-1_2",
                            "ACCACAATCTCTCGCA-1_2",
                            "ATGGAGGGTCCATAGT-1_2",
                            "CTCCAACCATCAGCTA-1_2",
                            "TTGTTGTAGGGCAATC-1_2",
                            "GGCACGTTCCTCGCAT-1_2_1",
                            "CCTCAACCAGTCGGTC-1_2",
                            "AGTTAGCTCTATCACT-1_2",
                            "TCTTGCGAGCCAGACA-1_2",
                            "AAAGGTAGTTACGGAG-1_2_1",
                            "GCGTGCACATGACTAC-1_2",
                            "TTCCTAACAGTTCACA-1_2",
                            "GGGCTCAGTATCGTAC-1_1",
                            "GATCCCTGTGTTGCCG-1_1_1",
                            "TGAGGTTGTACTTGTG-1_2",
                            "CGTCAAAAGAGCACTG-1_2",
                            "TAGAGTCCAGGGTTGA-1_2",
                            "GAGTGTTAGAAGAACG-1_2",
                            "GCCAGGTTCGCCGAGT-1_2",
                            "AGTAACCGTACCAGAG-1_2_1",
                            "TGTTCTACATCGAAGG-1_2",
                            "ACAGCCGAGTAATTGG-1_2_1",
                            "GGGTTTATCGCTTGCT-1_2",
                            "TCCCAGTTCAGCTTCC-1_1",
                            "CTGAGCGTCTGCTCTG-1_2",
                            "GATTTCTCAGGTCCGT-1_2",
                            "CATCAAGCACCGGTCA-1_2_1",
                            "CATTGTTGTGAATTGA-1_2",
                            "CCGGACAGTAACTGCT-1_2",
                            "GTGGAGAAGAGGGCGA-1_2",
                            "ATCATTCCAAGAGGCT-1_2",
                            "ATGGAGGAGTCATCGT-1_2",
                            "ATTTCTGAGTTTGGCT-1_1",
                            "TACTTCACATCTTTCA-1_2",
                            "GGCTTTCGTTGCCGCA-1_2",
                            "ACCAACAGTAGCTTTG-1_2",
                            "GAAATGATCCGTAGTA-1_2",
                            "TCCTCGATCCGTATAG-1_2",
                            "TACGTCCGTACTGCGC-1_2_1",
                            "CGTGAATCATCAGCGC-1_1",
                            "TCCTGCAGTGATTAGA-1_2",
                            "CTCCGATAGGGATCAC-1_2",
                            "GAACGTTAGGCGCTTC-1_2_1",
                            "ATGAAAGCATCAGTGT-1_2_1",
                            "TCAGTGAAGCAAACAT-1_2_1",
                            "CTACAGATCATCTACT-1_2_1",
                            "TTAGGCAAGCAAGTGC-1_2",
                            "CCGGGTAAGGTTCATC-1_2",
                            "CTTGATTCATGACGAG-1_1_1",
                            "ACCTACCAGGCTCACC-1_1_1",
                            "ATTCTACGTGAGTAAT-1_2_1",
                            "GGGTTATGTTCCTAGA-1_2_1",
                            "CCTTCAGTCGATCCCT-1_1",
                            "ACAGCCGTCCTCTCTT-1_2",
                            "AATGCCACAGCAGTAG-1_1_1",
                            "AGTTAGCGTGGAATGC-1_2",
                            "CATTCATGTAACTTCG-1_2_1",
                            "CGAAGGAAGGTGATAT-1_1",
                            "TCATATCCAAGTATAG-1_2",
                            "ACTGATGAGCCTGAAG-1_1",
                            "ATCGGCGGTGAGTTTC-1_2",
                            "AGTCATGTCGCCAATA-1_2",
                            "ACATGCAAGGTGGGTT-1_1",
                            "TTCTAACGTCAACATC-1_1_1",
                            "GAGTTACAGGGTTAGC-1_1",
                            "CATACAGTCTACGGGC-1_2_1",
                            "ATTCCCGAGGGTTGCA-1_1",
                            "ATACTTCCACGGCCAT-1_1_1",
                            "CATGCAACAAGTGATA-1_1_1",
                            "GTGTTAGTCTTTCAGT-1_1",
                            "GTGAGCCCACGCCAGT-1_2_1",
                            "GTGTGATTCCGGACGT-1_1",
                            "AAGATAGAGTTGCTCA-1_1_1",
                            "CGCCATTTCTCGGGAC-1_1",
                            "TCCGAAAAGGGCTGAT-1_2",
                            "CAAGGGACAGGACGAT-1_1",
                            "GTCTGTCGTTGACTGT-1_1_1",
                            "TCCTAATGTACCTTCC-1_2",
                            "CGCATGGAGTAAGCAT-1_2",
                            "TCGGATAAGAGTACCG-1_2",
                            "CTATAGGGTATCCCTC-1_2",
                            "TGGAGGAAGCCTCACG-1_1_1",
                            "GCAACATGTCTCTCAC-1_2",
                            "AAGACTCTCTTTACAC-1_1",
                            "CAAAGAACAGAAATCA-1_2",
                            "CATCCGTAGGCACGAT-1_1",
                            "TTCTAGTGTTACCGTA-1_1_1",
                            "AACCCAAAGCAAGTGC-1_2",
                            "AAGTGAAAGTCGAAAT-1_1",
                            "CACATGACACATATGC-1_2",
                            "AACGAAAAGATCGCTT-1_1_1",
                            "CTTCCGAAGCAAGTGC-1_1",
                            "GAAGCCCAGTTGGAGC-1_1",
                            "GAATAGATCAGAGCGA-1_2_1",
                            "CCGGTAGTCTGTTCAT-1_2_1",
                            "GAGAGGTTCAAGTCGT-1_1_1",
                            "GCAGTTAAGCACGATG-1_1",
                            "AGGCTGCTCGATCCCT-1_2_1",
                            "TTTGGTTCAAATTAGG-1_1",
                            "GTAAGTCAGCAGAAAG-1_2",
                            "GTGGCGTCATCGTCCT-1_1_1",
                            "TCACTATTCCGCACGA-1_1_1",
                            "GAGGGATGTCGTGCCA-1_1",
                            "ATTCTACGTATCAAGA-1_2_1",
                            "TGAATCGCAGCAATTC-1_1",
                            "TTGTTTGTCTAGCAAC-1_1_1",
                            "ACCTACCAGTTGGAAT-1_1",
                            "CTGAGCGCAGTATGAA-1_1_1",
                            "CCATAAGTCAGTGTCA-1_2_1",
                            "ACGCACGGTCGTATGT-1_1_1",
                            "ACCAACAGTGAGCTCC-1_1_1",
                            "CATGCCTCAGTCGTTA-1_1",
                            "TCGGGACGTTGCCAAT-1_1",
                            "CTCACTGCACCGTCTT-1_2_1",
                            "CGTTAGAAGAAAGCGA-1_1",
                            "CCTTCAGAGTGGCGAT-1_2_1",
                            "ACTGTGAAGGTTGCCC-1_1",
                            "ATCCACCGTATGGGAC-1_1",
                            "TGTACAGAGGTAGTCG-1_1_1",
                            "TCTATACGTTGGATCT-1_1_1",
                            "CACAACAAGAAATCCA-1_1",
                            "ACTGATGGTACTCCCT-1_1",
                            "TGTAACGTCTGTCTCG-1_1",
                            "TTGAACGCAGTGCGCT-1_1_1",
                            "CCTACGTAGATTGACA-1_1_1",
                            "GTGGGAACACAACGTT-1_2",
                            "GTAGAAATCAAACCCA-1_1",
                            "TGACAGTGTCTGCATA-1_1_1",
                            "CGATGGCTCAGCGTCG-1_1_1",
                            "ATGATCGAGGCGTTAG-1_1",
                            "TCTTCCTTCATGCGGC-1_1",
                            "TGCTCCAAGACCTCAT-1_1_1",
                            "GATTTCTAGTTCTACG-1_2_1",
                            "CGCCAGACACCACTGG-1_1",
                            "TCCTCGAAGTCAGCCC-1_1_1",
                            "AACAGGGCATACCGTA-1_1",
                            "ATGGAGGCAGAGGCTA-1_1",
                            "CGCATGGCATCGTGGC-1_1",
                            "TTCAGGATCAGTCATG-1_2_1",
                            "GAGTCATTCTCAACCC-1_2_1",
                            "TTCATGTGTACGTGAG-1_2",
                            "ACTATGGAGCTACGTT-1_2",
                            "TGAGGAGGTTGCAACT-1_2_1",
                            "AATGCCATCTACACTT-1_2",
                            "TGACCCTTCGGCCCAA-1_2",
                            "TGCAGATCAAAGAGTT-1_2",
                            "GGATCTATCCTTATGT-1_1",
                            "GTGGTTACATGACGTT-1_1",
                            "TTCAGGAAGCCTGACC-1_1_1",
                            "GCCCAGAAGCTCTATG-1_1",
                            "GGGATCCAGTAAATGC-1_2",
                            "GTAAGTCCACAACGAG-1_2",
                            "AGCTTCCGTCCTTGTC-1_1",
                            "AACGTCACAAGATGGC-1_2",
                            "TGGGCGTAGCAGGTCA-1_2_1",
                            "CAGATCATCATTGCTT-1_1",
                            "CTCCTCCCAAGGCGTA-1_2",
                            "AACACACGTCACTGAT-1_1_1",
                            "GGAGGTACAACTCGTA-1_1",
                            "CGACAGCCATACAGAA-1_2",
                            "AATAGAGGTCAACATC-1_2_1",
                            "GGTGGCTCAACCGACC-1_1",
                            "ACCGTTCTCAAAGACA-1_2_1",
                            "GGTGTTATCAAGCTGT-1_1_1",
                            "ATCCCTGGTTACACAC-1_2",
                            "ACCTGTCCATCTGTTT-1_2",
                            "TCGATTTGTTGTTGTG-1_2_1",
                            "GGGATCCGTCCAAAGG-1_2_1",
                            "CAAGCTAGTGTCTAAC-1_1_1",
                            "TAACCAGGTGGCTAGA-1_2_1",
                            "TACTTGTCACATATGC-1_2_1",
                            "CCCTGATAGTTCGGTT-1_2_1",
                            "TGATTCTGTCTCAGAT-1_2_1",
                            "CTCCGATAGGCCTTCG-1_2_1",
                            "ATACCTTCAGAAATCA-1_2_1",
                            "ACTTAGGAGCCTGGAA-1_2_1",
                            "ATATCCTCATGGCACC-1_1",
                            "TTCACGCGTCGCTCGA-1_2",
                            "TGTTGGATCATCACTT-1_2",
                            "AGTTCGAAGCAGTAAT-1_2_1",
                            "ATCGGCGAGGAGAATG-1_2",
                            "CCGGGTATCTACACAG-1_2"),invert=T)
# dimplot
Dimplot(seurat.obj.combined, group.by= "celltype_undefined")
ggsave("results/SCT.CCA/data input & merge/undefined_subtype_dimplot_res0.1.pdf",width = 7,height = 5)

# save RDS file
saveRDS(seurat.obj.combined,file = "results/SCT.CCA/data input & merge/goat.ON.snRNA_SCT.CCA.rds")
